language: java

jdk:
  - openjdk17

before_install:
  - ./gradlew --version
  - echo "reposilite_user=${AR_USER}" >> $HOME/.gradle/gradle.properties
  - echo "reposilite_password=${AR_PASSWORD}" >> $HOME/.gradle/gradle.properties

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: "build/libs/*.jar"
  skip_cleanup: true
  on:
    branch: master
    tags: true

after_deploy:
  - ./gradlew clean build publish
