language: java

jdk:
  - openjdk11

before_install:
  - ./gradlew --version
  - echo "nexusUrl=${AR_URL}" >> $HOME/.gradle/gradle.properties
  - echo "nexusUsername=${AR_USER}" >> $HOME/.gradle/gradle.properties
  - echo "nexusPassword=${AR_PASSWORD}" >> $HOME/.gradle/gradle.properties

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: "build/libs/*.jar"
  skip_cleanup: true
  on:
    branch: master
    tags: true

after_deploy:
  - ./gradlew clean build upload