plugins {
    id 'java'
    id 'idea'
    id 'maven-publish'
    id 'com.github.ben-manes.versions' version '0.53.0'
}

group = 'cordelia'
version = '6.0.1.RELEASE'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
}

repositories {
    mavenCentral()
    maven {
        url = "https://maven.sergeybochkov.com"
    }
}

dependencies {
    implementation platform('com.konghq:unirest-java-bom:4.7.4')
    implementation 'com.konghq:unirest-java-core'
    implementation 'com.konghq:unirest-modules-jackson'
    implementation platform('tools.jackson:jackson-bom:3.0.4')
    implementation 'tools.jackson.core:jackson-databind'

    compileOnly 'ch.qos.logback:logback-classic:1.5.27'
    testImplementation 'ch.qos.logback:logback-classic:1.5.27'

    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
    testCompileOnly 'org.projectlombok:lombok:1.18.42'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.42'

    testImplementation 'org.junit.jupiter:junit-jupiter:6.0.2'
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

publishing {
    repositories {
        maven {
            url = "https://maven.sergeybochkov.com/releases"
            credentials {
                username = "$reposilite_user"
                password = "$reposilite_password"
            }
        }
    }
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}

tasks.named('dependencyUpdates').configure {
    rejectVersionIf {
        return  ['.*-alpha\\d+', '.*-m\\d+$', '.*-rc\\d+'].any { part ->
            it.candidate.version.toLowerCase().matches(part)
        }
    }
}
